In [1]:
import numpy as np

### P3 - Basic Data types

In [6]:
5 // 3

1

In [8]:
5 % 3

2

### P4 - Lists in Python

In [12]:
# all

x = [1, 2, 3, None]
all(x)

False

In [13]:
# extend 

a = [1, 2, 3]
b = [4, 5, 6]
a.extend(b)
a

[1, 2, 3, 4, 5, 6]

In [20]:
# 'insert' does not replace

a = [1, 2, 3]
a.insert(1, 99)
a

[1, 99, 2, 3]

In [21]:
# does replace

a = [1, 2, 3]
a[2] = 99
a

[1, 2, 99]

In [22]:
# remove 

a = [1, 99, 2]
a.remove(99)
a

[1, 2]

In [25]:
# pop

a = [1, 2, 3]
a.pop(1)
a

[1, 3]

In [27]:
# sort 

a = [1, 3, 2]
a.sort()
a

[1, 2, 3]

In [28]:
# 'reverse' does not sort

a = [1, 3, 2]
a.reverse()
a

[2, 3, 1]

In [29]:
# count

a = [1, 1, 3, 2, 1]
a.count(1)

3

In [30]:
# clear

a = [1, 2, 3]
a.clear()

### P5 - Arrays in Python

In [3]:
a = np.array([[1, 2], [3, 4]])

In [6]:
# axis
np.sum(a, axis=0)

array([4, 6])

In [9]:
# dtype, otherwise is float

np.zeros((2, 2), dtype="int64")

array([[0, 0],
       [0, 0]])

In [12]:
# full

a = np.full((2, 2), 10)
a

array([[10, 10],
       [10, 10]])

In [20]:
# endpoint

a = np.linspace(0, 10, 10, dtype="int64", endpoint=False)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# list vs np.array
# in list, replacing the subset does not change the original array

a = [1, 2, 3]
b = a[1:]
b[0] = 99
print(b)
print(a)

[99, 3]
[1, 2, 3]


In [28]:
# list vs np.array
# in np.array, replacing the subset does change the original array

a = np.array([1, 2, 3])
b = a[1:]
b[0] = 99
print(b)
print(a)

[99  3]
[ 1 99  3]


In [36]:
# slicing

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

a[[0, 2, 1], [0, 0, 2]]

array([1, 7, 6])

In [37]:
# axis

np.max(a, axis=0)

array([7, 8, 9])

In [38]:
# argmin/argmax, returns the index for the min/max

np.argmin(a, axis=0)

array([0, 0, 0])

In [39]:
np.argmax(a, axis=1)

array([2, 2, 2])

### P6 - Arrays in Python

In [42]:
# reshape

a = np.array([
    [1, 2],
    [3, 4]
])

a.reshape(-1)

array([1, 2, 3, 4])

In [51]:
# ravel, changes in subset will appear in the original array

a = np.array([
    [1 , 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])

b = a.ravel()
print(b)
b[0] = 99
print(b)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[99  2  3  4  5  6  7  8  9 10 11 12]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
# flatten, changes in subset will NOT appear in the original array

a = np.array([
    [1 , 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])

b = a.flatten()
print(b)
b[0] = 99
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [54]:
# squeeze, drops extra dims

a = np.array([[[
    [1 , 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]]])

print(a.shape)
b = np.squeeze(a)
print(b.shape)

(1, 1, 3, 4)
(3, 4)


In [62]:
# concatenate

x = np.array([[1, 2], [3, 4]])
y = np.array([[11, 12], [13, 14]])
z0 = np.concatenate((x, y), axis=0)
print(z0)
print(z0.shape)
print("=" * 10)
z1 = np.concatenate((x, y), axis=1)
print(z1)
print(z1.shape)

[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]
(4, 2)
[[ 1  2 11 12]
 [ 3  4 13 14]]
(2, 4)


In [63]:
# stack, note an extra dim

z = np.stack((x, y), axis=0)
print(z)
print(z.shape)

[[[ 1  2]
  [ 3  4]]

 [[11 12]
  [13 14]]]
(2, 2, 2)


In [64]:
# column stack

z = np.column_stack((x, y))
print(z)
print(z.shape)

[[ 1  2 11 12]
 [ 3  4 13 14]]
(2, 4)


In [65]:
# hstack

z = np.hstack((x, y))
print(z)
print(z.shape)

[[ 1  2 11 12]
 [ 3  4 13 14]]
(2, 4)


In [66]:
# vstack

z = np.vstack((x, y))
print(z)
print(z.shape)

[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]
(4, 2)


In [72]:
# split, equal dim

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

a, b, c = np.split(x, 3)
print(a, b, c, sep='\n')

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [75]:
# array_split, un-equal dim

a, b = np.array_split(x, 2)
print(a, a.shape, sep='\n')
print("=" * 5)
print(b, b.shape, sep='\n')

[[1 2 3]
 [4 5 6]]
(2, 3)
=====
[[7 8 9]]
(1, 3)


In [84]:
# vsplit

np.vsplit(x, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [89]:
# hsplit

np.hsplit(x, 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [92]:
# tile

x = np.array([
    [1, 2],
    [3, 4]
])

np.tile(x, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [93]:
# broadcasting, adding two arrays with different shapes

x = np.array([
    [1, 2, 3, 4],
    [11, 12, 13, 14],
    [22, 33, 44, 55]
])
y = np.array([10, 20, 30 , 40])
x + y

array([[11, 22, 33, 44],
       [21, 32, 43, 54],
       [32, 53, 74, 95]])

### P7 - Tuple in Python

In [94]:
x = 1, 2, 3
type(x)

tuple

In [96]:
# concat two tuples

x = (1, 2, 3)
y = (4, 5, 6)
x + y

(1, 2, 3, 4, 5, 6)

In [101]:
# concat a tuple and a list

x = [1, 2, 3]
y = (4, 5, 6)
z1 = [*x, *y]
print(z1)
z2 = (*x, *y)
print(z2)

[1, 2, 3, 4, 5, 6]
(1, 2, 3, 4, 5, 6)


In [111]:
# flatten tuple

x = (1, 2, 3)
y = (x, x, x)
sum(y, ())

(1, 2, 3, 1, 2, 3, 1, 2, 3)

In [117]:
# index

x = (1, 2, 99)
x.index(99)

2

In [118]:
# count

x = (1, 1, 1, 2, 3)
x.count(1)

3

In [120]:
# tuples are allowed in sets

x = {(1, 2), (3, 4)}

In [119]:
# lists are not allowed in sets

x = {[1, 2], [3, 4]}

TypeError: unhashable type: 'list'

In [123]:
# dict keys can be tuple
x = {
    ("a", "b"): ["c", "d"],
    ("e", "f"): ["g", "H"]
}

x["a", "b"]

['c', 'd']

In [122]:
# dict keys cannot be list

x = {
    ["a", "b"]: ["c", "d"],
    ("e", "f"): ["g", "H"]
}

TypeError: unhashable type: 'list'

In [128]:
# flatten nested tuple 

x = (1, 2, 3)
y = (x, x, x)

[j for i in y for j in i]

[1, 2, 3, 1, 2, 3, 1, 2, 3]